### ISSUE TITLE
mac에서는 git clone이 되는데 windows에서는 git clone이 안되는 이유

### ISSUE THREAD

**Issue by jaewon1676** [codeisneverodd/programmers-coding-test#11]
https://young-cow.tistory.com/47?category=982994

windows에서는 파일명에 허용하지 않는 문자가 몇개 있네요
확인 해보니 level_1에 수박수박수박?이라는 파일 명이 있네요 오늘이 수요일이니 경현님께서 파일명 수정 해주시면 좋을 것 같습니다!

**Comment by codeisneverodd** [comment]
이슈 확인 후 수정 완료하였습니다. 제보해주셔서 감사합니다. 😸

**Comment by jaewon1676** [comment]
다시 git clone 해보니 이제 문제없이 clone 됩니다 :)
