### ISSUE TITLE
안녕하세요 cpp로 풀이한 코드를 js로 포팅해주실 수 있는 분을 구하고있습니다.

### ISSUE THREAD

**Issue by kim-sung-jee** [codeisneverodd/programmers-coding-test#119]
프로그래머스 문제들을 풀기 시작했는데 
생각보다 답이나 해설이 공개가 안된 문제들도 많이 존재하더라고요
이 레포지토리에 풀이나 해설을 기여하고 싶은데 제가 자바스크립트 문법도 잘 모르는 터라 ㅠㅠ
cpp로 작성된 코드를 js로 포팅하고 올려주실 분을 구하고 있습니다

**Comment by codeisneverodd** [comment]
저희 레포에 관심 가져주셔서 감사합니다!
현재는 원활한 관리를 위해 JS 해설만 받고 있지만, 향후 언어도 받는 것을 목표로 하고 있습니다.
또한 PR 방식이 아닌 GitHub API 를 이용한 더 간단한 기여 방법을 고려하고 있습니다.
레포 팀의 개인 정비가 끝나는대로 다시 돌아오겠습니다. 감사합니다 😄

**Comment by codeisneverodd** [comment]
편하게 이슈 오픈해두셔도 괜찮아요! 다시 close 하셔도 됩니다 👍
