### ISSUE TITLE
리드미 수정안

### ISSUE THREAD

**Issue by codeisneverodd** [codeisneverodd/programmers-coding-test#12]
# 참고한 링크
https://github.com/rajephon/programmers_training
에서 리드미의 좋은 형식을 발견해서 이슈 올립니다
# 변경하고 싶은 내용
기존에는 풀이 문제 수만 나와있는데
<img width="528" alt="image" src="https://user-images.githubusercontent.com/54318460/160783440-0979a61c-9c1c-44de-9036-b04fd5dacf20.png">
와 같이 표로 나타내준 것이  풀이를 찾아보기에 참 보기 좋은 것 같습니다! 
여러분들 의견은 어떠신가요? 동의하신다면 수정은 제가 하겠습니다!

**Comment by chaerin-dev** [comment]
너무 좋아요! 동의합니다!

**Comment by jaewon1676** [comment]
동의합니다!

**Comment by prove-ability** [comment]
동의합니다!
