### ISSUE TITLE
파일명 오타

### ISSUE THREAD

**Issue by jariita** [codeisneverodd/programmers-coding-test#29]
level-1 >> 히샤드-수.js : [하샤드-수.js]여야 합니다.
level-2 >> K-번째수.js : [K번째수.js] 여야 합니다.
level-3 >> 2_x_n_타일링.js : [2-x-n-타일링.js] 여야 합니다.

파일명 3개가 잘못되었습니다.

그 외 예외 )
수박수박수박수박수박수.js - windows에서 불가능한 파일명 '?'를 제거.
H-Index.js - 띄어쓰기를 '-'로 표현하는 것과 리터럴 그대로('-') 쓰는 것이 겹침.
N-Queen.js - 위와 동일.

**Comment by codeisneverodd** [comment]
1. 와 '히' 가 아니라 '하' 이군요! 감사합니다. 바로 수정하겠습니다.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/54318460/163575581-7b4845bf-c4c5-40e9-92db-9ca4e989e161.png">

2. K 번째 수 제보감사합니다. 레벨 폴더도 틀렸네요. 바로 수정하겠습니다!
3. 확인하였습니다! 바로 수정하겠습니다.

그 외)
리터럴이 겹치는 것을 생각 못했네요. @cruelladevil '\'같은 이스케이프 문자를 넣어서 표현하는 것이 좋을까요?

**Comment by jariita** [comment]
일단 테이블을 만들때 예외처리 할 경우의 수가 몇 가지 있어서 처리해두었습니다.
```js
function checkException(title) {
  switch (title) {
    case '수박수박수박수박수박수':
      return '수박수박수박수박수박수?';
    case 'H Index':
      return 'H-Index';
    case 'N Queen':
      return 'N-Queen';
    case '오픈채팅방':
      return '오픈채팅방 ';
    default:
      return title;
  }
}
```
'오픈채팅방'의 경우는 [문제 페이지](https://programmers.co.kr/learn/courses/30)에서 '오픈채팅방 '으로 되어있습니다.

리터럴의 경우 말씀하신 ''같이 이스케이프 문자를 넣어서 표현하면,
H'-'Index.js가 되는데,
```js
const fileName = `H'-'Index.js`;
const title = fileName
  .split('-').join(' ') // H' 'Index.js
  .replaceAll(/' '/g, '-') // H-Index.js
  .slice(0, -3) // H-Index
```
이렇게 리터럴을 중간에 처리할 수 있습니다.
허나 문제 중에서 리터럴이 쓰인 경우가 N-Queen, H-Index 밖에 없어서 크게 상관은 없을 듯 합니다.

**Comment by cruelladevil** [comment]
> 1. 와 '히' 가 아니라 '하' 이군요! 감사합니다. 바로 수정하겠습니다.
> 
> <img alt="image" width="354" src="https://user-images.githubusercontent.com/54318460/163575581-7b4845bf-c4c5-40e9-92db-9ca4e989e161.png">
> 
> 2. K 번째 수 제보감사합니다. 레벨 폴더도 틀렸네요. 바로 수정하겠습니다!
> 3. 확인하였습니다! 바로 수정하겠습니다.
> 
> 그 외) 리터럴이 겹치는 것을 생각 못했네요. @cruelladevil ''같은 이스케이프 문자를 넣어서 표현하는 것이 좋을까요?

**Comment by codeisneverodd** [comment]
해당 예외가 많아지면 모르겠지만, 현재로써는 문제가 없군요!
해주신 파일 전부 읽어봤습니다 너무 멋지네요
테스트용 브랜치를 생성해서 yml 파일에 테스트용 브랜치 추가와 build.js 에서 README 양식만 변형하여 반영하였습니다!
👍 기여해주셔서 감사합니다! 앞으로도 더 많은 프로젝트를 같이 할 수 있으면 좋겠네요! 넘 잘하십니다 😄

**Comment by codeisneverodd** [comment]
제가 이전에 했던 답변에서 이스케이프 문자가 정말 이스케이프 문자라서 표현이 안됐네요! 
`\`를 썼는데 마크다운 형식상 `''` 으로 보이네요 😅

**Comment by codeisneverodd** [comment]
지금까지 풀어진 문제를 아스키코드 순으로 정렬해서 표에 표시를 하고 싶었지만 수작업으로 하려면 너무 복잡해서 우선 표를 추가하지 않고 있었는데, 센스있게 추가해주셔서 감탄했습니다 👍👍

**Comment by jariita** [comment]
Windows에서 파일명으로 백슬래쉬(`\`)도 아마 안될겁니다.
이스케이프라는 것이 결국 우리가 쓰고자 하는 문자가 로직에 있을때 리터럴 그대로 사용하고자 탈출하는 방법을 만드는 것이니,
어떤 형태이든 상관은 없을 것 같습니다.

페이지에 있는 문제 전체에서 `-`이 쓰인 문제는 저 두 문제밖에 없습니다.
말씀하신대로 추후 새로운 문제에서 `-`가 들어가는 문제가 생긴다면 예외를 추가해줘야하는 번거로움이 생길 수 있긴 합니다.
그럴 경우 위와 같이 이스케이프 로직을 만드는게 편할지도 모릅니다. :)

저 또한 프로젝트에 기여하면서 즐거운 경험을 했습니다👍👍
