### ISSUE TITLE
해당 레퍼지토리를 SEO(Search Engine Optimization) 할 수 있을까요?

### ISSUE THREAD

**Issue by codeisneverodd** [codeisneverodd/programmers-coding-test#31]
# 해당 레퍼지토리를 SEO(Search Engine Optimization) 할 수 있을까요?
## 🧐 현재 상태
'프로그래머스 모든 문제 풀이 github' 라는 키워드로 구글 검색을 하였을 때, 상단에 나타나기는 하지만 
'프로그래머스 해설', '프로그래머스 코딩테스트 해설' 등으로 검색하였을 때 검색 결과에 나타나지 않습니다.

## 😎 요구 사항
- '프로그래머스 해설', '프로그래머스 코딩테스트 해설', '프로그래머스 javascript 해설' 으로 검색 하였을 때 검색 결과의 우선적으로 노출 될 수 있도록 README 등을 개선한다.

다양한 의견을 받고 있습니다! 아이디어가 있고 해결 가능하신 분은 자유롭게 의견 남겨주시고, 해당 레퍼지토리에 적극적으로 반영하겠습니다 😄 
프로젝트에 기여해주신 분은 감사한 마음을 담아 README에 GitHub 닉네임과 개인 페이지를 첨부해드리고 있습니다 👍

**Comment by prove-ability** [comment]
프로젝트 이름, About, Topics, Readme 말고도 Stars, Watchers, and Forks 에도 영향을 받는다고 나오네요 :D

[Link](https://www.developermarkepear.com/article/github-search-engine-optimization)

**Comment by codeisneverodd** [comment]
@prove-ability 오호 그렇군요! 열심히 레포를 알리고 다녀야겠군요 🤣

**Comment by codevilot** [comment]
몇 개의 사이트를 검색해보면서 체크하게 된 것이 지금 이런 Issue 페이지는, 이슈의 제목을, 그리고 https://github.com/codeisneverodd/programmers-coding-test 이 메인 깃 같은 경우에는 About이 title이 됩니다.그리고 현재 About은 "⭐️ 프로그래머스 코딩테스트를 통과한 JavaScript 해답을 찾아보세요!"이죠 About을 "프로그래머스 코딩테스트 해설"과 같이 수정해 보는건 어떨까요? 아니면 "프로그래머스 코딩테스트 해설 - ⭐️ 프로그래머스 코딩테스트를 통과한 JavaScript 해답을 찾아보세요!"과 같이요 (아마 뒷 부분은 내용 중복이 있기 때문에 전자의 것이 더 좋을꺼 같네요)

**Comment by codeisneverodd** [comment]
@codevilot 좋은 의견 감사합니다!!
이에 따라 About을 다음과 같이 개정합니다.
"프로그래머스 코딩테스트 해설 모음집"
