### ISSUE TITLE
⭐️ README 를 개선해주실 분을 모집합니다 ⭐️

### ISSUE THREAD

**Issue by codeisneverodd** [codeisneverodd/programmers-coding-test#45]
본 레퍼지토리의 README 를 개선해주실 분을 모집합니다! (모집기간: 채택 시 종료)
리드미 완성본을 제출해주실 필요없이, 기본적인 틀을 제시하시면 대화를 통해 개선 해나갈 예정입니다!

## 🎁 기여 혜택
1. README 최상단 **Contributors에 이름 추가 및 개인 홍보자료**(블로그 링크 등 원하는 링크)를 삽입해드립니다!
> 유입이 계속 늘어나고 있는 만큼, 자기 PR에 좋은 포인트가 될 수 있다고 생각합니다 😁
2. 2022년 4월 26일 기준,지난 **2주간 약 3000 View, 180 명의 Unique Visitor**를 가지고 있는 레퍼지토리이며 꾸준히 성장 중인 README를 작성해보실 수 있습니다!
<img width="692" alt="image" src="https://user-images.githubusercontent.com/54318460/165222031-dd92da85-b81d-486b-8be3-d529c7cb191a.png">

3. 약소하지만 **기프티콘**을 드릴 예정입니다!

## 🔥 README 제안 방법
본 이슈에 생각하시는 README 양식을 답글로 달아주시면 됩니다!

### 🪶 README 의 방향성(1번이 가장 중요한 항목입니다.)
1. **Star 를 클릭**하도록 유도하여야합니다, 레퍼지토리의 성장을 위함입니다.
2. **Contributors 가 상단**에 위치하여야합니다, 레퍼지토리의 성장을 위함입니다.
3. 레퍼지토리에 처음 들어왔을 때, **"검색을 통해 문제의 해답을 찾을 수 있다"라는 사실**을  바로 인지할 수 있도록 하여야합니다.
5. 새롭게 문제를 추가하실 분들을 위하여, 기여하시는 분이 **커밋 컨벤션**을 보고 작성 할 수 있도록 유도하여야합니다.
### 🪶 추가로 고려하실 사항
1. **문제 표는 자동완성**으로 만들어지기 때문에 `/// 문제 표 ///` 와 같은 형식으로 채워두시면 됩니다.

**Comment by le2sky** [comment]
@codeisneverodd
완전한 개선사항은 아니지만 없는 문제를 골라서 푸려고 하는 사용자가 있을 수도 있으니
아직 풀리지 않은 문제도 README에 작성되어 있으면 속도감있게 풀리지 않을까 기대합니다!

* 추가로 해설이나 접근방법에 대한 내용을 따로 작성하는 파일이 있다면 CICD 구축해서 정적 사이트 배포도 불가능하지는
  않을 것 같습니다!

**Comment by codeisneverodd** [comment]
@le2sky 좋은 의견 감사합니다!! 
1. 풀리지 않은 문제를 자동으로 추가하고 그것을 명시할 방안을 고안해보겠습니다. 👍
2. 풀이 외에 해설 부분을 별도의 파일로 유지하는 방안을 팀원들과 상의후 효과적이다 판단되면 적용하겠습니다 😁
3. 정적사이트 배포는 다행히 예정되어있습니다!! 현재는 데이터 수집 및 사이트 설계 단계를 진행하고 있습니다 😆

**Comment by jariita** [comment]
@codeisneverodd 
1. 풀리지 않은 문제는 한 번만 추가하면 됩니다. 그 이후 풀린 문제와 풀리지 않은 문제를 구분하는 것에 의의를 두어야 할 것 같습니다.
ex)
✅  | 풀린 문제
❌  | 풀리지 않은 문제

**Comment by codeisneverodd** [comment]
@cruelladevil 남겨주신 내용이 잘 이해가 안되었는데, 한 번만 추가하면 된다는 것이 적혀있는 풀이는 없더라도 해당하는 파일을 만들어야한다는 것 일까요?

**Comment by jariita** [comment]
@codeisneverodd
README.md에 전체 문제 목록을 한 번만 업데이트 하면 된다는 뜻입니다.
그 이후 풀이 파일이 있는 것과 없는 것을 비교해 풀이 여부를 결정하여 표시할 수 있습니다.
다만, 현재 README.md를 업데이트 하는 코드로는 level 구별이 안 되어있기 때문에 전체 문제를 README.md에 바로 업데이트 하지는 못하고 새로 코드를 만들어서 level 구분을 해서 넣는 작업을 한 번 하면 될 것 같습니다.
또한, 후에 프로그래머스에 새로운 문제들이 추가됨에 따라 문제들을 업데이트 해주는 것에 있어 일정 기간마다 체크하도록 ci를 작성하는 것도 좋아보입니다.
